name: Weekly Republish

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 (UTC)

jobs:
  republish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds